In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from sklearn.linear_model import LogisticRegression 

In [8]:
from sklearn.metrics import accuracy_score #performance measure

In [25]:
df=pd.read_csv("mail_data.csv")

In [26]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [27]:
df.duplicate().count()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [28]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
5567    False
5568    False
5569    False
5570    False
5571    False
Length: 5572, dtype: bool

In [29]:
df.duplicated().count()

np.int64(5572)

In [30]:
df.drop_duplicates(inplace=True)

In [31]:
mess=df['Message']

In [32]:
mess

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5157, dtype: object

In [33]:
cat=df['Category']

In [34]:
cat


0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5157, dtype: object

In [35]:
mess_train,mess_test,cat_train,cat_test=train_test_split(mess,cat,test_size=0.2)

In [36]:
mess_train.size()

TypeError: 'int' object is not callable

In [37]:
mess_train


493                      Sorry,in meeting I'll call later
5433    You're gonna have to be way more specific than...
502                                  When can ü come out?
4330    1Apple/Day=No Doctor. 1Tulsi Leaf/Day=No Cance...
1985    Urgent! Please call 09061743810 from landline....
                              ...                        
4559    PISS IS TALKING IS SOMEONE THAT REALISE U THAT...
1327                      Sorry, was in the bathroom, sup
956     Sorry i now then c ur msg... Yar lor so poor t...
2756                                We r outside already.
2587    If you don't respond imma assume you're still ...
Name: Message, Length: 4125, dtype: object

In [38]:
mess_test


4814            i can call in  &lt;#&gt;  min if thats ok
4202    Wylie update: my weed dealer carlos went to fr...
605                                Meet after lunch la...
1404     cool. We will have fun practicing making babies!
2896                            Went to ganesh dress shop
                              ...                        
2939    Hey i've booked the pilates and yoga lesson al...
2356    Hello, my love ! How went your day ? Are you a...
240     U 447801259231 have a secret admirer who is lo...
176     Let me know when you've got the money so carlo...
2598    Got fujitsu, ibm, hp, toshiba... Got a lot of ...
Name: Message, Length: 1032, dtype: object

In [39]:
cv=CountVectorizer(stop_words='english')

In [41]:
cv.fit_transform(mess_train)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 31371 stored elements and shape (4125, 7417)>

In [42]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [44]:
X = tfidf.fit_transform(mess).toarray()

In [45]:
X


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [48]:
cat_encoder = encoder.fit_transform(cat)

In [49]:
cat_encoder

array([0, 0, 1, ..., 0, 0, 0])

In [50]:
X.shape

(5157, 3000)

In [51]:
y=cat_encoder

In [52]:
y.shape

(5157,)

In [53]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [54]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [55]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [56]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.8934108527131783
[[808  97]
 [ 13 114]]
0.5402843601895735


In [57]:
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9777131782945736
[[905   0]
 [ 23 104]]
1.0


In [58]:
import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))